version: "3.7"

services:
  django:
    image: faycelgnfd/stroke-predictor-back 
    volumes:
      - django_static_volume:/usr/src/app/static
    ports:
      - "8000:8000"
   
    command: python manage.py runserver 0.0.0.0:8000
  react:
      image: faycelgnfd/stroke-predictor-front
      volumes:
        - react_static_volume:/usr/src/app/build/static
      ports:
        - "3000:3000"
      env_file:
        - .env
  
      depends_on:
        - django

  
 

volumes:
  django_static_volume:
  react_static_volume: